apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: my-project
roleRef:
  kind: Role
  name: strimzi-cluster-operator-namespaced
  apiGroup: rbac.authorization.k8s.io
